/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belajarjframe;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class PesanMakanMinum extends javax.swing.JFrame {

    /**
     * Creates new form PesanMakanMinum
     */
    public PesanMakanMinum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbNasiRames = new javax.swing.JCheckBox();
        cbNasiGoreng = new javax.swing.JCheckBox();
        cbEsTehManis = new javax.swing.JCheckBox();
        cbTehManisHangat = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfPorsiNasiRames = new javax.swing.JTextField();
        tfPorsiNasiGoreng = new javax.swing.JTextField();
        tfPorsiEsTehManis = new javax.swing.JTextField();
        tfPorsiTehManisHangat = new javax.swing.JTextField();
        tfBiayaNasiGoreng = new javax.swing.JTextField();
        tfBiayaNasiRames = new javax.swing.JTextField();
        tfBiayaEsTehManis = new javax.swing.JTextField();
        tfBiayaTehManisHangat = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnPesan = new javax.swing.JButton();
        tfTotalBiaya = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taView = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        btnBayar = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pesan Makan Minum");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Makanan & Minuman");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Biaya");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Porsi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Harga");

        cbNasiRames.setText("Nasi Rames");

        cbNasiGoreng.setText("Nasi Goreng");

        cbEsTehManis.setText("Es Teh Manis");

        cbTehManisHangat.setText("Teh Manis Hangat");

        jLabel6.setText("Rp. 12.000");

        jLabel7.setText("Rp. 10.000");

        jLabel8.setText("Rp. 5.000");

        jLabel9.setText("Rp. 4000");

        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        jLabel10.setText("Total");

        jLabel11.setText("Pesanan Anda Adalah :");

        taView.setColumns(20);
        taView.setRows(5);
        jScrollPane1.setViewportView(taView);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBayar)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(tfTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNasiRames)
                                    .addComponent(cbTehManisHangat)
                                    .addComponent(cbEsTehManis)
                                    .addComponent(cbNasiGoreng))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPorsiNasiRames, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(tfPorsiNasiGoreng)
                                    .addComponent(tfPorsiEsTehManis)
                                    .addComponent(tfPorsiTehManisHangat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfBiayaTehManisHangat, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(tfBiayaEsTehManis)
                                    .addComponent(tfBiayaNasiGoreng)
                                    .addComponent(tfBiayaNasiRames)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(289, 388, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(52, 52, 52)))))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNasiRames)
                    .addComponent(jLabel6)
                    .addComponent(tfPorsiNasiRames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBiayaNasiRames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNasiGoreng)
                    .addComponent(jLabel7)
                    .addComponent(tfPorsiNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBiayaNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEsTehManis)
                    .addComponent(jLabel8)
                    .addComponent(tfPorsiEsTehManis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBiayaEsTehManis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTehManisHangat)
                    .addComponent(jLabel9)
                    .addComponent(tfPorsiTehManisHangat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBiayaTehManisHangat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesan)
                    .addComponent(tfTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnExit))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        int totalBiaya = 0;

        if (cbNasiRames.isSelected()) {
            int porsiNasiRames
                    = Integer.parseInt(tfPorsiNasiRames.getText());
            int biayaNasiRames;

            biayaNasiRames = porsiNasiRames * 12000;
            tfBiayaNasiRames.setText("" + biayaNasiRames);

            totalBiaya += biayaNasiRames;
            tfTotalBiaya.setText("" + totalBiaya);
        }

        if (cbNasiGoreng.isSelected()) {
            int porsiNasiGoreng
                    = Integer.parseInt(tfPorsiNasiGoreng.getText());
            int biayaNasiGoreng;

            biayaNasiGoreng = porsiNasiGoreng * 10000;
            tfBiayaNasiGoreng.setText("" + biayaNasiGoreng);

            totalBiaya += biayaNasiGoreng;
            tfTotalBiaya.setText("" + totalBiaya);
        }
        if (cbEsTehManis.isSelected()) {
            int porsiEsTehManis
                    = Integer.parseInt(tfPorsiEsTehManis.getText());
            int biayaEsTehManis;

            biayaEsTehManis = porsiEsTehManis * 5000;
            tfBiayaEsTehManis.setText("" + biayaEsTehManis);

            totalBiaya += biayaEsTehManis;
            tfTotalBiaya.setText("" + totalBiaya);
        }

        if (cbTehManisHangat.isSelected()) {
            int porsiTehManisHangat
                    = Integer.parseInt(tfPorsiTehManisHangat.getText());
            int biayaTehManisHangat;

            biayaTehManisHangat = porsiTehManisHangat * 4000;
            tfBiayaTehManisHangat.setText("" + biayaTehManisHangat);

            totalBiaya += biayaTehManisHangat;
            tfTotalBiaya.setText("" + totalBiaya);
        }
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        String tampil = "";
        int totalBiaya = 0;

        if (cbNasiRames.isSelected()) {
            int porsiNasiRames
                    = Integer.parseInt(tfPorsiNasiRames.getText());
            int biayaNasiRames;

            biayaNasiRames = porsiNasiRames * 12000;
            tfBiayaNasiRames.setText("" + biayaNasiRames);

            totalBiaya += biayaNasiRames;
            tfTotalBiaya.setText("" + totalBiaya);

            tampil += cbNasiRames.getText() + " : Rp 12.000" + " x "
                    + porsiNasiRames + " = " + biayaNasiRames + "\n";
        }

        if (cbNasiGoreng.isSelected()) {
            int porsiNasiGoreng
                    = Integer.parseInt(tfPorsiNasiGoreng.getText());
            int biayaNasiGoreng;

            biayaNasiGoreng = porsiNasiGoreng * 10000;
            tfBiayaNasiGoreng.setText("" + biayaNasiGoreng);
            totalBiaya += biayaNasiGoreng;
            tfTotalBiaya.setText("" + totalBiaya);

            tampil += cbNasiGoreng.getText() + " : Rp 10.000" + " x "
                    + porsiNasiGoreng + " = " + biayaNasiGoreng + "\n";
        }

        if (cbEsTehManis.isSelected()) {
            int porsiEsTehManis
                    = Integer.parseInt(tfPorsiEsTehManis.getText());
            int biayaEsTehManis;

            biayaEsTehManis = porsiEsTehManis * 5000;
            tfBiayaNasiGoreng.setText("" + biayaEsTehManis);

            totalBiaya += biayaEsTehManis;
            tfTotalBiaya.setText("" + totalBiaya);

            tampil += cbEsTehManis.getText() + " : Rp 5.000" + " x "
                    + porsiEsTehManis + " = " + biayaEsTehManis + "\n";
        }

        if (cbTehManisHangat.isSelected()) {
            int porsiTehManisHangat
                    = Integer.parseInt(tfPorsiTehManisHangat.getText());
            int biayaTehManisHangat;

            biayaTehManisHangat = porsiTehManisHangat * 4000;
            tfBiayaTehManisHangat.setText("" + biayaTehManisHangat);

            totalBiaya += biayaTehManisHangat;
            tfTotalBiaya.setText("" + totalBiaya);

            tampil += cbTehManisHangat.getText() + " : Rp 4.000" + " x "
                    + porsiTehManisHangat + " = " + biayaTehManisHangat + "\n";
        }

        taView.setText(tampil + "======================" + "\n" + "Total Bayar \t:Rp. " + totalBiaya);
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        cbNasiRames.setSelected(false);
        cbNasiGoreng.setSelected(false);
        cbEsTehManis.setSelected(false);
        cbTehManisHangat.setSelected(false);

        tfPorsiNasiRames.setText("");
        tfPorsiNasiGoreng.setText("");
        tfPorsiEsTehManis.setText("");
        tfPorsiTehManisHangat.setText("");

        tfBiayaNasiRames.setText("");
        tfBiayaNasiGoreng.setText("");
        tfBiayaEsTehManis.setText("");
        tfBiayaTehManisHangat.setText("");

        tfTotalBiaya.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cbNasiRames.setSelected(false);
        cbNasiGoreng.setSelected(false);
        cbEsTehManis.setSelected(false);
        cbTehManisHangat.setSelected(false);

        tfPorsiNasiRames.setText("");
        tfPorsiNasiGoreng.setText("");
        tfPorsiEsTehManis.setText("");
        tfPorsiTehManisHangat.setText("");

        tfBiayaNasiRames.setText("");
        tfBiayaNasiGoreng.setText("");
        tfBiayaEsTehManis.setText("");
        tfBiayaTehManisHangat.setText("");

        tfTotalBiaya.setText("");
        taView.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this,
                "Apakah Anda Ingin Keluar?",
                "Exit",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanMakanMinum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanMakanMinum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox cbEsTehManis;
    private javax.swing.JCheckBox cbNasiGoreng;
    private javax.swing.JCheckBox cbNasiRames;
    private javax.swing.JCheckBox cbTehManisHangat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea taView;
    private javax.swing.JTextField tfBiayaEsTehManis;
    private javax.swing.JTextField tfBiayaNasiGoreng;
    private javax.swing.JTextField tfBiayaNasiRames;
    private javax.swing.JTextField tfBiayaTehManisHangat;
    private javax.swing.JTextField tfPorsiEsTehManis;
    private javax.swing.JTextField tfPorsiNasiGoreng;
    private javax.swing.JTextField tfPorsiNasiRames;
    private javax.swing.JTextField tfPorsiTehManisHangat;
    private javax.swing.JTextField tfTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
